import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { League_Spartan } from "next/font/google"; 
import "./globals.css";
import Navbar from "@/modules/Navbar";
import { LanguageProvider } from "@/context/Context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spartan = League_Spartan({
  variable: "--font-spartan", 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${spartan.variable} antialiased`}>
        <LanguageProvider>
        {children}
        </LanguageProvider>
      </body>
    </html>
  );
}